# -*- coding: utf-8 -*-
"""Index&Slicing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jq4riSfJegquWK4OolzuSkvO7Uwnn6x-

##1. Extracting By Index Position
"""

from string import ascii_lowercase

ascii_lowercase

len(ascii_lowercase)

list(ascii_lowercase)

import pandas as pd

#pd.Series(list)

pd.Series(ascii_lowercase)

letters = list(ascii_lowercase)

letters

pd.Series(letters)

pd.Series(letters).head(7)

#OR 
alphabet = pd.Series(letters)

alphabet.head(7)

# Slicing the pandas series which is same as list slicing
alphabet[3]

# let's practice some Slicing in pandas series. 
alphabet[:4]

alphabet[3:10]

alphabet[-3:]

alphabet[20:-1] # Same as python upper bound is not inclusive but lower bound is.

"""# 2.Accessing Elements By label"""

from string import ascii_uppercase

ascii_uppercase

# accessing to each elements by custome indexing or label:
labeled_alphabet = pd.Series(data = list(ascii_lowercase), index =list(ascii_uppercase))

labeled_alphabet.head(7)

labeled_alphabet["D":"F"]

labeled_alphabet[3:6]

# Negative indexing
labeled_alphabet["U":]

